package com.beust.swt

const val SPEED_FACTOR = 4
const val PERIOD_MILLISECONDS = 100L

const val WIDTH = 280
const val HEIGHT = 192
const val MIXED_HEIGHT = 160
const val WIDTH_FACTOR = 2
const val HEIGHT_FACTOR = 2
const val ACTUAL_WIDTH = WIDTH * WIDTH_FACTOR
const val ACTUAL_HEIGHT = HEIGHT * HEIGHT_FACTOR
const val ACTUAL_MIXED_HEIGHT = MIXED_HEIGHT * HEIGHT_FACTOR

const val MAIN_WINDOW_HEIGHT = 650
const val BYTE_BUFFER_HEIGHT = MAIN_WINDOW_HEIGHT - 150

